spring:
  application:
    name: schemamanager

  data:
    mongodb:
      uri: mongodb+srv://pratick13:Ke8bxduVgTSMKdqs@cluster0.rfftg.mongodb.net/syncbridgeDB?retryWrites=true&w=majority

server:
  port: 8000
