spring:
  application:
    name: schemamanager

  data:
    mongodb:
      uri: mongodb+srv://pratick13:Ke8bxduVgTSMKdqs@cluster0.rfftg.mongodb.net/syncbridgeDB?retryWrites=true&w=majority

server:
  port: 8000

logging:
  level:
    com.example: DEBUG
    org.springframework.web: ERROR
  file:
    name: app.log
    path: logs
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
