spring:
  application:
    name: schemamanager

  data:
    mongodb:
      uri: mongodb+srv://pratick13:Ke8bxduVgTSMKdqs@cluster0.rfftg.mongodb.net/syncbridgeDB?retryWrites=true&w=majority

grpc:
  server:
    port: 9090
    health-check-enabled: true
  client:
    test-server:
      address: "localhost:9090"

logging:
  level:
    root: INFO
    com.mongodb: ERROR
    org.springframework.web: ERROR
    com.syncbridge: DEBUG
  file:
    name: logs/app.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %level [%t]: %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} %level [%t]: %msg%n"


